### ISSUE TITLE
tests failing on node 4

### ISSUE THREAD

**Issue by jasonpincin** [joyent/node-consulite#3]
Tests are failing on the LTS release of Node (4).

**Comment by jasonpincin** [comment]
So I tracked this down to an issue in Wreck, I think. If I change this line:

https://github.com/hapijs/wreck/blob/master/lib/index.js#L146

``` javascript
this.emit('request', uri, options);
```

to be:

``` javascript
process[internals.emitSymbol].emit('request', uri, options);
```

then the Consulite tests pass in Node v4. 

Wreck is doing some interesting things in the constructors to share a single EventEmitter instance, and it's possible some minor variation in Object.assign, or EventEmitter property descriptors are causing this to fail in Node v4. 

Trying to put together a PR against Wreck with a test that demonstrates this failure (along with a fix), but simply changing the above line causes other Wreck tests to fail (in both Node v4 and Node v6) which is concerning as I would think those two lines should be interchangeable based on my admittedly shallow understanding of Wreck.

The way this is manifesting, by the way, is that `process[Symbol.for('wreck')].once('request', () => {})`, is not seeing the `once` handler cleared after it fires. On the subsequent firing of a once handler (of the same event), then both are cleared and replaced with an `undefined`, which then blows up all future `emit` calls. It's very strange behavior and certainly points to some invalid state within the EventEmitter, likely caused by the way it's being setup. My guess is one or more of the properties EventEmitter expects to find on itself are being created privately on each Wreck request instance, while others are shared across all. 

This is just a guess. With your deeper understanding of the Wreck codebase, you may arrive at a fix faster than me.

**Comment by geek** [comment]
@jasonpincin the other tests will fail in wreck because they rely on wreck to be the emitter. 

I remember a process event emitter issue in node core in v4, let me see if I can track it down.

**Comment by jasonpincin** [comment]
@geek Yep - I did away with that issue in the example PR hapijs/wreck#146.
